# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/yanry/dma/dma_ip/dma_ip.runs/synth_1/dma_core_wrap_v.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu19eg-ffvc1760-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/yanry/dma/dma_ip/dma_ip.cache/wt [current_project]
set_property parent.project_path /home/yanry/dma/dma_ip/dma_ip.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/yanry/dma/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /home/yanry/dma/dma_ip/dma_ip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/yanry/dma/src/axi_pkg.sv
  /home/yanry/dma/src/axi_atop_filter.sv
  /home/yanry/dma/src/axi_burst_splitter.sv
  /home/yanry/dma/src/cf_math_pkg.sv
  /home/yanry/dma/src/axi_demux.sv
  /home/yanry/dma/src/idma_pkg.sv
  /home/yanry/dma/src/axi_err_slv.sv
  /home/yanry/dma/src/axi_intf.sv
  /home/yanry/dma/src/axi_lite_to_reg.sv
  /home/yanry/dma/src/axi_to_axi_lite.sv
  /home/yanry/dma/src/axi_to_reg.sv
  /home/yanry/dma/src/counter.sv
  /home/yanry/dma/src/delta_counter.sv
  /home/yanry/dma/src/dma_core_wrap.sv
  /home/yanry/dma/src/dma_core_wrap_sv.sv
  /home/yanry/dma/src/fall_through_register.sv
  /home/yanry/dma/src/fifo_v2.sv
  /home/yanry/dma/src/fifo_v3.sv
  /home/yanry/dma/src/id_queue.sv
  /home/yanry/dma/src/idma_axi_lite_transport_layer.sv
  /home/yanry/dma/src/idma_axi_transport_layer.sv
  /home/yanry/dma/src/idma_backend.sv
  /home/yanry/dma/src/idma_buffer.sv
  /home/yanry/dma/src/idma_channel_coupler.sv
  /home/yanry/dma/src/idma_error_handler.sv
  /home/yanry/dma/src/idma_legalizer.sv
  /home/yanry/dma/src/idma_nd_midend.sv
  /home/yanry/dma/src/idma_obi_transport_layer.sv
  /home/yanry/dma/src/idma_reg64_2d_frontend_reg_pkg.sv
  /home/yanry/dma/src/idma_reg64_2d_frontend.sv
  /home/yanry/dma/src/idma_reg64_2d_frontend_reg_top.sv
  /home/yanry/dma/src/idma_reg64_frontend_reg_pkg.sv
  /home/yanry/dma/src/idma_reg64_frontend.sv
  /home/yanry/dma/src/idma_reg64_frontend_reg_top.sv
  /home/yanry/dma/src/idma_stream_fifo.sv
  /home/yanry/dma/src/idma_transfer_id_gen.sv
  /home/yanry/dma/src/lzc.sv
  /home/yanry/dma/src/onehot_to_bin.sv
  /home/yanry/dma/src/popcount.sv
  /home/yanry/dma/src/prim_subreg.sv
  /home/yanry/dma/src/prim_subreg_arb.sv
  /home/yanry/dma/src/prim_subreg_ext.sv
  /home/yanry/dma/src/reg_intf.sv
  /home/yanry/dma/src/rr_arb_tree.sv
  /home/yanry/dma/src/spill_register.sv
  /home/yanry/dma/src/spill_register_flushable.sv
  /home/yanry/dma/src/stream_arbiter.sv
  /home/yanry/dma/src/stream_arbiter_flushable.sv
  /home/yanry/dma/src/stream_fifo.sv
  /home/yanry/dma/src/stream_fork.sv
  /home/yanry/dma/src/stream_register.sv
}
read_verilog -library xil_defaultlib /home/yanry/dma/src/dma_core_wrap_v.v
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/yanry/dma/dma_ip/dma_ip.srcs/utils_1/imports/synth_1/dma_core_wrap_v.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top dma_core_wrap_v -part xczu19eg-ffvc1760-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dma_core_wrap_v.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file dma_core_wrap_v_utilization_synth.rpt -pb dma_core_wrap_v_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
