# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yanry/dma/axi_xbar_test/axi_xbar_test.srcs/sources_1/bd/design_2/ip/design_2_axi_bram_ctrl_1_0/design_2_axi_bram_ctrl_1_0.xci
# IP: The module: 'design_2_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yanry/dma/axi_xbar_test/axi_xbar_test.gen/sources_1/bd/design_2/ip/design_2_axi_bram_ctrl_1_0/design_2_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/yanry/dma/axi_xbar_test/axi_xbar_test.srcs/sources_1/bd/design_2/ip/design_2_axi_bram_ctrl_1_0/design_2_axi_bram_ctrl_1_0.xci
# IP: The module: 'design_2_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yanry/dma/axi_xbar_test/axi_xbar_test.gen/sources_1/bd/design_2/ip/design_2_axi_bram_ctrl_1_0/design_2_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
