-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Thu Jan 23 22:28:18 2025
-- Host        : dell running 64-bit Ubuntu 20.04.6 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_axi_cdc_v_0_1_stub.vhdl
-- Design      : design_1_axi_cdc_v_0_1
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu19eg-ffvc1760-2-i
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    src_clk_i : in STD_LOGIC;
    src_rst_ni : in STD_LOGIC;
    src_req_aw_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    src_req_aw_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    src_req_aw_len : in STD_LOGIC_VECTOR ( 7 downto 0 );
    src_req_aw_size : in STD_LOGIC_VECTOR ( 2 downto 0 );
    src_req_aw_burst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    src_req_aw_lock : in STD_LOGIC;
    src_req_aw_cache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    src_req_aw_prot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    src_req_aw_qos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    src_req_aw_region : in STD_LOGIC_VECTOR ( 3 downto 0 );
    src_req_aw_atop : in STD_LOGIC_VECTOR ( 5 downto 0 );
    src_req_aw_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    src_req_aw_valid : in STD_LOGIC;
    src_rsp_aw_ready : out STD_LOGIC;
    src_req_w_data : in STD_LOGIC_VECTOR ( 511 downto 0 );
    src_req_w_strb : in STD_LOGIC_VECTOR ( 63 downto 0 );
    src_req_w_last : in STD_LOGIC;
    src_req_w_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    src_req_w_valid : in STD_LOGIC;
    src_rsp_w_ready : out STD_LOGIC;
    src_rsp_b_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    src_rsp_b_resp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    src_rsp_b_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    src_rsp_b_valid : out STD_LOGIC;
    src_req_b_ready : in STD_LOGIC;
    src_req_ar_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    src_req_ar_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    src_req_ar_len : in STD_LOGIC_VECTOR ( 7 downto 0 );
    src_req_ar_size : in STD_LOGIC_VECTOR ( 2 downto 0 );
    src_req_ar_burst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    src_req_ar_lock : in STD_LOGIC;
    src_req_ar_cache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    src_req_ar_prot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    src_req_ar_qos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    src_req_ar_region : in STD_LOGIC_VECTOR ( 3 downto 0 );
    src_req_ar_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    src_req_ar_valid : in STD_LOGIC;
    src_rsp_ar_ready : out STD_LOGIC;
    src_rsp_r_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    src_rsp_r_data : out STD_LOGIC_VECTOR ( 511 downto 0 );
    src_rsp_r_resp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    src_rsp_r_last : out STD_LOGIC;
    src_rsp_r_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    src_rsp_r_valid : out STD_LOGIC;
    src_req_r_ready : in STD_LOGIC;
    dst_clk_i : in STD_LOGIC;
    dst_rst_ni : in STD_LOGIC;
    dst_req_aw_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    dst_req_aw_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    dst_req_aw_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dst_req_aw_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dst_req_aw_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dst_req_aw_lock : out STD_LOGIC;
    dst_req_aw_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dst_req_aw_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dst_req_aw_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dst_req_aw_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dst_req_aw_atop : out STD_LOGIC_VECTOR ( 5 downto 0 );
    dst_req_aw_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    dst_req_aw_valid : out STD_LOGIC;
    dst_rsp_aw_ready : in STD_LOGIC;
    dst_req_w_data : out STD_LOGIC_VECTOR ( 511 downto 0 );
    dst_req_w_strb : out STD_LOGIC_VECTOR ( 63 downto 0 );
    dst_req_w_last : out STD_LOGIC;
    dst_req_w_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    dst_req_w_valid : out STD_LOGIC;
    dst_rsp_w_ready : in STD_LOGIC;
    dst_rsp_b_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    dst_rsp_b_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dst_rsp_b_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    dst_rsp_b_valid : in STD_LOGIC;
    dst_req_b_ready : out STD_LOGIC;
    dst_req_ar_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    dst_req_ar_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    dst_req_ar_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dst_req_ar_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dst_req_ar_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dst_req_ar_lock : out STD_LOGIC;
    dst_req_ar_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dst_req_ar_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dst_req_ar_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dst_req_ar_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dst_req_ar_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    dst_req_ar_valid : out STD_LOGIC;
    dst_rsp_ar_ready : in STD_LOGIC;
    dst_rsp_r_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    dst_rsp_r_data : in STD_LOGIC_VECTOR ( 511 downto 0 );
    dst_rsp_r_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dst_rsp_r_last : in STD_LOGIC;
    dst_rsp_r_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    dst_rsp_r_valid : in STD_LOGIC;
    dst_req_r_ready : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_axi_cdc_v_0_1,axi_cdc_v,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "package_project";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "src_clk_i,src_rst_ni,src_req_aw_id[0:0],src_req_aw_addr[63:0],src_req_aw_len[7:0],src_req_aw_size[2:0],src_req_aw_burst[1:0],src_req_aw_lock,src_req_aw_cache[3:0],src_req_aw_prot[2:0],src_req_aw_qos[3:0],src_req_aw_region[3:0],src_req_aw_atop[5:0],src_req_aw_user[0:0],src_req_aw_valid,src_rsp_aw_ready,src_req_w_data[511:0],src_req_w_strb[63:0],src_req_w_last,src_req_w_user[0:0],src_req_w_valid,src_rsp_w_ready,src_rsp_b_id[0:0],src_rsp_b_resp[1:0],src_rsp_b_user[0:0],src_rsp_b_valid,src_req_b_ready,src_req_ar_id[0:0],src_req_ar_addr[63:0],src_req_ar_len[7:0],src_req_ar_size[2:0],src_req_ar_burst[1:0],src_req_ar_lock,src_req_ar_cache[3:0],src_req_ar_prot[2:0],src_req_ar_qos[3:0],src_req_ar_region[3:0],src_req_ar_user[0:0],src_req_ar_valid,src_rsp_ar_ready,src_rsp_r_id[0:0],src_rsp_r_data[511:0],src_rsp_r_resp[1:0],src_rsp_r_last,src_rsp_r_user[0:0],src_rsp_r_valid,src_req_r_ready,dst_clk_i,dst_rst_ni,dst_req_aw_id[0:0],dst_req_aw_addr[63:0],dst_req_aw_len[7:0],dst_req_aw_size[2:0],dst_req_aw_burst[1:0],dst_req_aw_lock,dst_req_aw_cache[3:0],dst_req_aw_prot[2:0],dst_req_aw_qos[3:0],dst_req_aw_region[3:0],dst_req_aw_atop[5:0],dst_req_aw_user[0:0],dst_req_aw_valid,dst_rsp_aw_ready,dst_req_w_data[511:0],dst_req_w_strb[63:0],dst_req_w_last,dst_req_w_user[0:0],dst_req_w_valid,dst_rsp_w_ready,dst_rsp_b_id[0:0],dst_rsp_b_resp[1:0],dst_rsp_b_user[0:0],dst_rsp_b_valid,dst_req_b_ready,dst_req_ar_id[0:0],dst_req_ar_addr[63:0],dst_req_ar_len[7:0],dst_req_ar_size[2:0],dst_req_ar_burst[1:0],dst_req_ar_lock,dst_req_ar_cache[3:0],dst_req_ar_prot[2:0],dst_req_ar_qos[3:0],dst_req_ar_region[3:0],dst_req_ar_user[0:0],dst_req_ar_valid,dst_rsp_ar_ready,dst_rsp_r_id[0:0],dst_rsp_r_data[511:0],dst_rsp_r_resp[1:0],dst_rsp_r_last,dst_rsp_r_user[0:0],dst_rsp_r_valid,dst_req_r_ready";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of src_clk_i : signal is "xilinx.com:signal:clock:1.0 axi_src_clk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of src_clk_i : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of src_clk_i : signal is "XIL_INTERFACENAME axi_src_clk, ASSOCIATED_BUSIF axi_src, ASSOCIATED_RESET src_rst_ni, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of src_rst_ni : signal is "xilinx.com:signal:reset:1.0 axi_src_rst_n RST";
  attribute X_INTERFACE_MODE of src_rst_ni : signal is "slave";
  attribute X_INTERFACE_PARAMETER of src_rst_ni : signal is "XIL_INTERFACENAME axi_src_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of src_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 axi_src AWID";
  attribute X_INTERFACE_MODE of src_req_aw_id : signal is "slave";
  attribute X_INTERFACE_PARAMETER of src_req_aw_id : signal is "XIL_INTERFACENAME axi_src, DATA_WIDTH 512, PROTOCOL AXI4, ID_WIDTH 1, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of src_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 axi_src AWADDR";
  attribute X_INTERFACE_INFO of src_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 axi_src AWLEN";
  attribute X_INTERFACE_INFO of src_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 axi_src AWSIZE";
  attribute X_INTERFACE_INFO of src_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 axi_src AWBURST";
  attribute X_INTERFACE_INFO of src_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 axi_src AWLOCK";
  attribute X_INTERFACE_INFO of src_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 axi_src AWCACHE";
  attribute X_INTERFACE_INFO of src_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 axi_src AWPROT";
  attribute X_INTERFACE_INFO of src_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 axi_src AWQOS";
  attribute X_INTERFACE_INFO of src_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 axi_src AWREGION";
  attribute X_INTERFACE_INFO of src_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 axi_src AWUSER";
  attribute X_INTERFACE_INFO of src_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 axi_src AWVALID";
  attribute X_INTERFACE_INFO of src_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 axi_src AWREADY";
  attribute X_INTERFACE_INFO of src_req_w_data : signal is "xilinx.com:interface:aximm:1.0 axi_src WDATA";
  attribute X_INTERFACE_INFO of src_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 axi_src WSTRB";
  attribute X_INTERFACE_INFO of src_req_w_last : signal is "xilinx.com:interface:aximm:1.0 axi_src WLAST";
  attribute X_INTERFACE_INFO of src_req_w_user : signal is "xilinx.com:interface:aximm:1.0 axi_src WUSER";
  attribute X_INTERFACE_INFO of src_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 axi_src WVALID";
  attribute X_INTERFACE_INFO of src_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 axi_src WREADY";
  attribute X_INTERFACE_INFO of src_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 axi_src BID";
  attribute X_INTERFACE_INFO of src_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 axi_src BRESP";
  attribute X_INTERFACE_INFO of src_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 axi_src BUSER";
  attribute X_INTERFACE_INFO of src_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 axi_src BVALID";
  attribute X_INTERFACE_INFO of src_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 axi_src BREADY";
  attribute X_INTERFACE_INFO of src_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 axi_src ARID";
  attribute X_INTERFACE_INFO of src_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 axi_src ARADDR";
  attribute X_INTERFACE_INFO of src_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 axi_src ARLEN";
  attribute X_INTERFACE_INFO of src_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 axi_src ARSIZE";
  attribute X_INTERFACE_INFO of src_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 axi_src ARBURST";
  attribute X_INTERFACE_INFO of src_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 axi_src ARLOCK";
  attribute X_INTERFACE_INFO of src_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 axi_src ARCACHE";
  attribute X_INTERFACE_INFO of src_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 axi_src ARPROT";
  attribute X_INTERFACE_INFO of src_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 axi_src ARQOS";
  attribute X_INTERFACE_INFO of src_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 axi_src ARREGION";
  attribute X_INTERFACE_INFO of src_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 axi_src ARUSER";
  attribute X_INTERFACE_INFO of src_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 axi_src ARVALID";
  attribute X_INTERFACE_INFO of src_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 axi_src ARREADY";
  attribute X_INTERFACE_INFO of src_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 axi_src RID";
  attribute X_INTERFACE_INFO of src_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 axi_src RDATA";
  attribute X_INTERFACE_INFO of src_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 axi_src RRESP";
  attribute X_INTERFACE_INFO of src_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 axi_src RLAST";
  attribute X_INTERFACE_INFO of src_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 axi_src RUSER";
  attribute X_INTERFACE_INFO of src_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 axi_src RVALID";
  attribute X_INTERFACE_INFO of src_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 axi_src RREADY";
  attribute X_INTERFACE_INFO of dst_clk_i : signal is "xilinx.com:signal:clock:1.0 axi_dst_clk CLK";
  attribute X_INTERFACE_MODE of dst_clk_i : signal is "slave";
  attribute X_INTERFACE_PARAMETER of dst_clk_i : signal is "XIL_INTERFACENAME axi_dst_clk, ASSOCIATED_BUSIF axi_dst, ASSOCIATED_RESET dst_rst_ni, FREQ_TOLERANCE_HZ 0, PHASE 0.00, CLK_DOMAIN design_1_ddr4_0_0_c0_ddr4_ui_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dst_rst_ni : signal is "xilinx.com:signal:reset:1.0 axi_dst_rst_n RST";
  attribute X_INTERFACE_MODE of dst_rst_ni : signal is "slave";
  attribute X_INTERFACE_PARAMETER of dst_rst_ni : signal is "XIL_INTERFACENAME axi_dst_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dst_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWID";
  attribute X_INTERFACE_MODE of dst_req_aw_id : signal is "master";
  attribute X_INTERFACE_PARAMETER of dst_req_aw_id : signal is "XIL_INTERFACENAME axi_dst, DATA_WIDTH 512, PROTOCOL AXI4, ID_WIDTH 1, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.00, CLK_DOMAIN design_1_ddr4_0_0_c0_ddr4_ui_clk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dst_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWADDR";
  attribute X_INTERFACE_INFO of dst_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWLEN";
  attribute X_INTERFACE_INFO of dst_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWSIZE";
  attribute X_INTERFACE_INFO of dst_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWBURST";
  attribute X_INTERFACE_INFO of dst_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWLOCK";
  attribute X_INTERFACE_INFO of dst_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWCACHE";
  attribute X_INTERFACE_INFO of dst_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWPROT";
  attribute X_INTERFACE_INFO of dst_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWQOS";
  attribute X_INTERFACE_INFO of dst_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWREGION";
  attribute X_INTERFACE_INFO of dst_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWUSER";
  attribute X_INTERFACE_INFO of dst_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWVALID";
  attribute X_INTERFACE_INFO of dst_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 axi_dst AWREADY";
  attribute X_INTERFACE_INFO of dst_req_w_data : signal is "xilinx.com:interface:aximm:1.0 axi_dst WDATA";
  attribute X_INTERFACE_INFO of dst_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 axi_dst WSTRB";
  attribute X_INTERFACE_INFO of dst_req_w_last : signal is "xilinx.com:interface:aximm:1.0 axi_dst WLAST";
  attribute X_INTERFACE_INFO of dst_req_w_user : signal is "xilinx.com:interface:aximm:1.0 axi_dst WUSER";
  attribute X_INTERFACE_INFO of dst_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 axi_dst WVALID";
  attribute X_INTERFACE_INFO of dst_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 axi_dst WREADY";
  attribute X_INTERFACE_INFO of dst_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 axi_dst BID";
  attribute X_INTERFACE_INFO of dst_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 axi_dst BRESP";
  attribute X_INTERFACE_INFO of dst_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 axi_dst BUSER";
  attribute X_INTERFACE_INFO of dst_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 axi_dst BVALID";
  attribute X_INTERFACE_INFO of dst_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 axi_dst BREADY";
  attribute X_INTERFACE_INFO of dst_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARID";
  attribute X_INTERFACE_INFO of dst_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARADDR";
  attribute X_INTERFACE_INFO of dst_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARLEN";
  attribute X_INTERFACE_INFO of dst_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARSIZE";
  attribute X_INTERFACE_INFO of dst_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARBURST";
  attribute X_INTERFACE_INFO of dst_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARLOCK";
  attribute X_INTERFACE_INFO of dst_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARCACHE";
  attribute X_INTERFACE_INFO of dst_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARPROT";
  attribute X_INTERFACE_INFO of dst_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARQOS";
  attribute X_INTERFACE_INFO of dst_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARREGION";
  attribute X_INTERFACE_INFO of dst_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARUSER";
  attribute X_INTERFACE_INFO of dst_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARVALID";
  attribute X_INTERFACE_INFO of dst_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 axi_dst ARREADY";
  attribute X_INTERFACE_INFO of dst_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 axi_dst RID";
  attribute X_INTERFACE_INFO of dst_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 axi_dst RDATA";
  attribute X_INTERFACE_INFO of dst_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 axi_dst RRESP";
  attribute X_INTERFACE_INFO of dst_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 axi_dst RLAST";
  attribute X_INTERFACE_INFO of dst_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 axi_dst RUSER";
  attribute X_INTERFACE_INFO of dst_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 axi_dst RVALID";
  attribute X_INTERFACE_INFO of dst_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 axi_dst RREADY";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "axi_cdc_v,Vivado 2024.2";
begin
end;
