#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 19 18:43:13 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim axi_xbar_test2_behav -key {Behavioral:sim_1:Functional:axi_xbar_test2} -tclbatch axi_xbar_test2.tcl -protoinst "protoinst_files/design_2.protoinst" -view /home/yanry/dma/axi_xbar_test/axi_xbar_tb_behav.wcfg -log simulate.log"
xsim axi_xbar_test2_behav -key {Behavioral:sim_1:Functional:axi_xbar_test2} -tclbatch axi_xbar_test2.tcl -protoinst "protoinst_files/design_2.protoinst" -view /home/yanry/dma/axi_xbar_test/axi_xbar_tb_behav.wcfg -log simulate.log

