-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Thu Feb 13 16:34:50 2025
-- Host        : dell running 64-bit Ubuntu 20.04.6 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_axi_xbar_v_0_0_stub.vhdl
-- Design      : design_1_axi_xbar_v_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu19eg-ffvc1760-2-i
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    clk_i : in STD_LOGIC;
    rst_ni : in STD_LOGIC;
    slv0_req_aw_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_req_aw_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    slv0_req_aw_len : in STD_LOGIC_VECTOR ( 7 downto 0 );
    slv0_req_aw_size : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv0_req_aw_burst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    slv0_req_aw_lock : in STD_LOGIC;
    slv0_req_aw_cache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv0_req_aw_prot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv0_req_aw_qos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv0_req_aw_region : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv0_req_aw_atop : in STD_LOGIC_VECTOR ( 5 downto 0 );
    slv0_req_aw_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_req_aw_valid : in STD_LOGIC;
    slv0_rsp_aw_ready : out STD_LOGIC;
    slv0_req_w_data : in STD_LOGIC_VECTOR ( 63 downto 0 );
    slv0_req_w_strb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    slv0_req_w_last : in STD_LOGIC;
    slv0_req_w_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_req_w_valid : in STD_LOGIC;
    slv0_rsp_w_ready : out STD_LOGIC;
    slv0_rsp_b_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_rsp_b_resp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    slv0_rsp_b_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_rsp_b_valid : out STD_LOGIC;
    slv0_req_b_ready : in STD_LOGIC;
    slv0_req_ar_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_req_ar_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    slv0_req_ar_len : in STD_LOGIC_VECTOR ( 7 downto 0 );
    slv0_req_ar_size : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv0_req_ar_burst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    slv0_req_ar_lock : in STD_LOGIC;
    slv0_req_ar_cache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv0_req_ar_prot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv0_req_ar_qos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv0_req_ar_region : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv0_req_ar_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_req_ar_valid : in STD_LOGIC;
    slv0_rsp_ar_ready : out STD_LOGIC;
    slv0_rsp_r_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_rsp_r_data : out STD_LOGIC_VECTOR ( 63 downto 0 );
    slv0_rsp_r_resp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    slv0_rsp_r_last : out STD_LOGIC;
    slv0_rsp_r_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv0_rsp_r_valid : out STD_LOGIC;
    slv0_req_r_ready : in STD_LOGIC;
    slv1_req_aw_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_req_aw_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    slv1_req_aw_len : in STD_LOGIC_VECTOR ( 7 downto 0 );
    slv1_req_aw_size : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv1_req_aw_burst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    slv1_req_aw_lock : in STD_LOGIC;
    slv1_req_aw_cache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv1_req_aw_prot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv1_req_aw_qos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv1_req_aw_region : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv1_req_aw_atop : in STD_LOGIC_VECTOR ( 5 downto 0 );
    slv1_req_aw_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_req_aw_valid : in STD_LOGIC;
    slv1_rsp_aw_ready : out STD_LOGIC;
    slv1_req_w_data : in STD_LOGIC_VECTOR ( 63 downto 0 );
    slv1_req_w_strb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    slv1_req_w_last : in STD_LOGIC;
    slv1_req_w_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_req_w_valid : in STD_LOGIC;
    slv1_rsp_w_ready : out STD_LOGIC;
    slv1_rsp_b_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_rsp_b_resp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    slv1_rsp_b_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_rsp_b_valid : out STD_LOGIC;
    slv1_req_b_ready : in STD_LOGIC;
    slv1_req_ar_id : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_req_ar_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    slv1_req_ar_len : in STD_LOGIC_VECTOR ( 7 downto 0 );
    slv1_req_ar_size : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv1_req_ar_burst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    slv1_req_ar_lock : in STD_LOGIC;
    slv1_req_ar_cache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv1_req_ar_prot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    slv1_req_ar_qos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv1_req_ar_region : in STD_LOGIC_VECTOR ( 3 downto 0 );
    slv1_req_ar_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_req_ar_valid : in STD_LOGIC;
    slv1_rsp_ar_ready : out STD_LOGIC;
    slv1_rsp_r_id : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_rsp_r_data : out STD_LOGIC_VECTOR ( 63 downto 0 );
    slv1_rsp_r_resp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    slv1_rsp_r_last : out STD_LOGIC;
    slv1_rsp_r_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    slv1_rsp_r_valid : out STD_LOGIC;
    slv1_req_r_ready : in STD_LOGIC;
    slv2_req_aw_atop : in STD_LOGIC_VECTOR ( 5 downto 0 );
    mst0_req_aw_id : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_req_aw_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst0_req_aw_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst0_req_aw_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_req_aw_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    mst0_req_aw_lock : out STD_LOGIC;
    mst0_req_aw_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst0_req_aw_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_req_aw_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst0_req_aw_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst0_req_aw_atop : out STD_LOGIC_VECTOR ( 5 downto 0 );
    mst0_req_aw_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst0_req_aw_valid : out STD_LOGIC;
    mst0_rsp_aw_ready : in STD_LOGIC;
    mst0_req_w_data : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst0_req_w_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst0_req_w_last : out STD_LOGIC;
    mst0_req_w_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst0_req_w_valid : out STD_LOGIC;
    mst0_rsp_w_ready : in STD_LOGIC;
    mst0_rsp_b_id : in STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_rsp_b_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    mst0_rsp_b_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    mst0_rsp_b_valid : in STD_LOGIC;
    mst0_req_b_ready : out STD_LOGIC;
    mst0_req_ar_id : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_req_ar_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst0_req_ar_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst0_req_ar_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_req_ar_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    mst0_req_ar_lock : out STD_LOGIC;
    mst0_req_ar_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst0_req_ar_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_req_ar_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst0_req_ar_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst0_req_ar_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst0_req_ar_valid : out STD_LOGIC;
    mst0_rsp_ar_ready : in STD_LOGIC;
    mst0_rsp_r_id : in STD_LOGIC_VECTOR ( 2 downto 0 );
    mst0_rsp_r_data : in STD_LOGIC_VECTOR ( 63 downto 0 );
    mst0_rsp_r_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    mst0_rsp_r_last : in STD_LOGIC;
    mst0_rsp_r_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    mst0_rsp_r_valid : in STD_LOGIC;
    mst0_req_r_ready : out STD_LOGIC;
    mst1_req_aw_id : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_req_aw_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst1_req_aw_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst1_req_aw_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_req_aw_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    mst1_req_aw_lock : out STD_LOGIC;
    mst1_req_aw_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst1_req_aw_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_req_aw_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst1_req_aw_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst1_req_aw_atop : out STD_LOGIC_VECTOR ( 5 downto 0 );
    mst1_req_aw_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst1_req_aw_valid : out STD_LOGIC;
    mst1_rsp_aw_ready : in STD_LOGIC;
    mst1_req_w_data : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst1_req_w_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst1_req_w_last : out STD_LOGIC;
    mst1_req_w_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst1_req_w_valid : out STD_LOGIC;
    mst1_rsp_w_ready : in STD_LOGIC;
    mst1_rsp_b_id : in STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_rsp_b_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    mst1_rsp_b_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    mst1_rsp_b_valid : in STD_LOGIC;
    mst1_req_b_ready : out STD_LOGIC;
    mst1_req_ar_id : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_req_ar_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst1_req_ar_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst1_req_ar_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_req_ar_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    mst1_req_ar_lock : out STD_LOGIC;
    mst1_req_ar_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst1_req_ar_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_req_ar_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst1_req_ar_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst1_req_ar_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst1_req_ar_valid : out STD_LOGIC;
    mst1_rsp_ar_ready : in STD_LOGIC;
    mst1_rsp_r_id : in STD_LOGIC_VECTOR ( 2 downto 0 );
    mst1_rsp_r_data : in STD_LOGIC_VECTOR ( 63 downto 0 );
    mst1_rsp_r_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    mst1_rsp_r_last : in STD_LOGIC;
    mst1_rsp_r_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    mst1_rsp_r_valid : in STD_LOGIC;
    mst1_req_r_ready : out STD_LOGIC;
    mst2_req_aw_id : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_req_aw_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst2_req_aw_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst2_req_aw_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_req_aw_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    mst2_req_aw_lock : out STD_LOGIC;
    mst2_req_aw_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst2_req_aw_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_req_aw_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst2_req_aw_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst2_req_aw_atop : out STD_LOGIC_VECTOR ( 5 downto 0 );
    mst2_req_aw_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst2_req_aw_valid : out STD_LOGIC;
    mst2_rsp_aw_ready : in STD_LOGIC;
    mst2_req_w_data : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst2_req_w_strb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst2_req_w_last : out STD_LOGIC;
    mst2_req_w_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst2_req_w_valid : out STD_LOGIC;
    mst2_rsp_w_ready : in STD_LOGIC;
    mst2_rsp_b_id : in STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_rsp_b_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    mst2_rsp_b_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    mst2_rsp_b_valid : in STD_LOGIC;
    mst2_req_b_ready : out STD_LOGIC;
    mst2_req_ar_id : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_req_ar_addr : out STD_LOGIC_VECTOR ( 63 downto 0 );
    mst2_req_ar_len : out STD_LOGIC_VECTOR ( 7 downto 0 );
    mst2_req_ar_size : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_req_ar_burst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    mst2_req_ar_lock : out STD_LOGIC;
    mst2_req_ar_cache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst2_req_ar_prot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_req_ar_qos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst2_req_ar_region : out STD_LOGIC_VECTOR ( 3 downto 0 );
    mst2_req_ar_user : out STD_LOGIC_VECTOR ( 0 to 0 );
    mst2_req_ar_valid : out STD_LOGIC;
    mst2_rsp_ar_ready : in STD_LOGIC;
    mst2_rsp_r_id : in STD_LOGIC_VECTOR ( 2 downto 0 );
    mst2_rsp_r_data : in STD_LOGIC_VECTOR ( 63 downto 0 );
    mst2_rsp_r_resp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    mst2_rsp_r_last : in STD_LOGIC;
    mst2_rsp_r_user : in STD_LOGIC_VECTOR ( 0 to 0 );
    mst2_rsp_r_valid : in STD_LOGIC;
    mst2_req_r_ready : out STD_LOGIC;
    rule0_idx : in STD_LOGIC_VECTOR ( 1 downto 0 );
    rule0_start_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rule0_end_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rule1_idx : in STD_LOGIC_VECTOR ( 1 downto 0 );
    rule1_start_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rule1_end_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rule2_idx : in STD_LOGIC_VECTOR ( 1 downto 0 );
    rule2_start_addr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    rule2_end_addr : in STD_LOGIC_VECTOR ( 63 downto 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_axi_xbar_v_0_0,axi_xbar_v,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "package_project";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "clk_i,rst_ni,slv0_req_aw_id[0:0],slv0_req_aw_addr[63:0],slv0_req_aw_len[7:0],slv0_req_aw_size[2:0],slv0_req_aw_burst[1:0],slv0_req_aw_lock,slv0_req_aw_cache[3:0],slv0_req_aw_prot[2:0],slv0_req_aw_qos[3:0],slv0_req_aw_region[3:0],slv0_req_aw_atop[5:0],slv0_req_aw_user[0:0],slv0_req_aw_valid,slv0_rsp_aw_ready,slv0_req_w_data[63:0],slv0_req_w_strb[7:0],slv0_req_w_last,slv0_req_w_user[0:0],slv0_req_w_valid,slv0_rsp_w_ready,slv0_rsp_b_id[0:0],slv0_rsp_b_resp[1:0],slv0_rsp_b_user[0:0],slv0_rsp_b_valid,slv0_req_b_ready,slv0_req_ar_id[0:0],slv0_req_ar_addr[63:0],slv0_req_ar_len[7:0],slv0_req_ar_size[2:0],slv0_req_ar_burst[1:0],slv0_req_ar_lock,slv0_req_ar_cache[3:0],slv0_req_ar_prot[2:0],slv0_req_ar_qos[3:0],slv0_req_ar_region[3:0],slv0_req_ar_user[0:0],slv0_req_ar_valid,slv0_rsp_ar_ready,slv0_rsp_r_id[0:0],slv0_rsp_r_data[63:0],slv0_rsp_r_resp[1:0],slv0_rsp_r_last,slv0_rsp_r_user[0:0],slv0_rsp_r_valid,slv0_req_r_ready,slv1_req_aw_id[0:0],slv1_req_aw_addr[63:0],slv1_req_aw_len[7:0],slv1_req_aw_size[2:0],slv1_req_aw_burst[1:0],slv1_req_aw_lock,slv1_req_aw_cache[3:0],slv1_req_aw_prot[2:0],slv1_req_aw_qos[3:0],slv1_req_aw_region[3:0],slv1_req_aw_atop[5:0],slv1_req_aw_user[0:0],slv1_req_aw_valid,slv1_rsp_aw_ready,slv1_req_w_data[63:0],slv1_req_w_strb[7:0],slv1_req_w_last,slv1_req_w_user[0:0],slv1_req_w_valid,slv1_rsp_w_ready,slv1_rsp_b_id[0:0],slv1_rsp_b_resp[1:0],slv1_rsp_b_user[0:0],slv1_rsp_b_valid,slv1_req_b_ready,slv1_req_ar_id[0:0],slv1_req_ar_addr[63:0],slv1_req_ar_len[7:0],slv1_req_ar_size[2:0],slv1_req_ar_burst[1:0],slv1_req_ar_lock,slv1_req_ar_cache[3:0],slv1_req_ar_prot[2:0],slv1_req_ar_qos[3:0],slv1_req_ar_region[3:0],slv1_req_ar_user[0:0],slv1_req_ar_valid,slv1_rsp_ar_ready,slv1_rsp_r_id[0:0],slv1_rsp_r_data[63:0],slv1_rsp_r_resp[1:0],slv1_rsp_r_last,slv1_rsp_r_user[0:0],slv1_rsp_r_valid,slv1_req_r_ready,slv2_req_aw_atop[5:0],mst0_req_aw_id[2:0],mst0_req_aw_addr[63:0],mst0_req_aw_len[7:0],mst0_req_aw_size[2:0],mst0_req_aw_burst[1:0],mst0_req_aw_lock,mst0_req_aw_cache[3:0],mst0_req_aw_prot[2:0],mst0_req_aw_qos[3:0],mst0_req_aw_region[3:0],mst0_req_aw_atop[5:0],mst0_req_aw_user[0:0],mst0_req_aw_valid,mst0_rsp_aw_ready,mst0_req_w_data[63:0],mst0_req_w_strb[7:0],mst0_req_w_last,mst0_req_w_user[0:0],mst0_req_w_valid,mst0_rsp_w_ready,mst0_rsp_b_id[2:0],mst0_rsp_b_resp[1:0],mst0_rsp_b_user[0:0],mst0_rsp_b_valid,mst0_req_b_ready,mst0_req_ar_id[2:0],mst0_req_ar_addr[63:0],mst0_req_ar_len[7:0],mst0_req_ar_size[2:0],mst0_req_ar_burst[1:0],mst0_req_ar_lock,mst0_req_ar_cache[3:0],mst0_req_ar_prot[2:0],mst0_req_ar_qos[3:0],mst0_req_ar_region[3:0],mst0_req_ar_user[0:0],mst0_req_ar_valid,mst0_rsp_ar_ready,mst0_rsp_r_id[2:0],mst0_rsp_r_data[63:0],mst0_rsp_r_resp[1:0],mst0_rsp_r_last,mst0_rsp_r_user[0:0],mst0_rsp_r_valid,mst0_req_r_ready,mst1_req_aw_id[2:0],mst1_req_aw_addr[63:0],mst1_req_aw_len[7:0],mst1_req_aw_size[2:0],mst1_req_aw_burst[1:0],mst1_req_aw_lock,mst1_req_aw_cache[3:0],mst1_req_aw_prot[2:0],mst1_req_aw_qos[3:0],mst1_req_aw_region[3:0],mst1_req_aw_atop[5:0],mst1_req_aw_user[0:0],mst1_req_aw_valid,mst1_rsp_aw_ready,mst1_req_w_data[63:0],mst1_req_w_strb[7:0],mst1_req_w_last,mst1_req_w_user[0:0],mst1_req_w_valid,mst1_rsp_w_ready,mst1_rsp_b_id[2:0],mst1_rsp_b_resp[1:0],mst1_rsp_b_user[0:0],mst1_rsp_b_valid,mst1_req_b_ready,mst1_req_ar_id[2:0],mst1_req_ar_addr[63:0],mst1_req_ar_len[7:0],mst1_req_ar_size[2:0],mst1_req_ar_burst[1:0],mst1_req_ar_lock,mst1_req_ar_cache[3:0],mst1_req_ar_prot[2:0],mst1_req_ar_qos[3:0],mst1_req_ar_region[3:0],mst1_req_ar_user[0:0],mst1_req_ar_valid,mst1_rsp_ar_ready,mst1_rsp_r_id[2:0],mst1_rsp_r_data[63:0],mst1_rsp_r_resp[1:0],mst1_rsp_r_last,mst1_rsp_r_user[0:0],mst1_rsp_r_valid,mst1_req_r_ready,mst2_req_aw_id[2:0],mst2_req_aw_addr[63:0],mst2_req_aw_len[7:0],mst2_req_aw_size[2:0],mst2_req_aw_burst[1:0],mst2_req_aw_lock,mst2_req_aw_cache[3:0],mst2_req_aw_prot[2:0],mst2_req_aw_qos[3:0],mst2_req_aw_region[3:0],mst2_req_aw_atop[5:0],mst2_req_aw_user[0:0],mst2_req_aw_valid,mst2_rsp_aw_ready,mst2_req_w_data[63:0],mst2_req_w_strb[7:0],mst2_req_w_last,mst2_req_w_user[0:0],mst2_req_w_valid,mst2_rsp_w_ready,mst2_rsp_b_id[2:0],mst2_rsp_b_resp[1:0],mst2_rsp_b_user[0:0],mst2_rsp_b_valid,mst2_req_b_ready,mst2_req_ar_id[2:0],mst2_req_ar_addr[63:0],mst2_req_ar_len[7:0],mst2_req_ar_size[2:0],mst2_req_ar_burst[1:0],mst2_req_ar_lock,mst2_req_ar_cache[3:0],mst2_req_ar_prot[2:0],mst2_req_ar_qos[3:0],mst2_req_ar_region[3:0],mst2_req_ar_user[0:0],mst2_req_ar_valid,mst2_rsp_ar_ready,mst2_rsp_r_id[2:0],mst2_rsp_r_data[63:0],mst2_rsp_r_resp[1:0],mst2_rsp_r_last,mst2_rsp_r_user[0:0],mst2_rsp_r_valid,mst2_req_r_ready,rule0_idx[1:0],rule0_start_addr[63:0],rule0_end_addr[63:0],rule1_idx[1:0],rule1_start_addr[63:0],rule1_end_addr[63:0],rule2_idx[1:0],rule2_start_addr[63:0],rule2_end_addr[63:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of clk_i : signal is "xilinx.com:signal:clock:1.0 clk_i CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of clk_i : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of clk_i : signal is "XIL_INTERFACENAME clk_i, ASSOCIATED_BUSIF slv0:slv1:slv2:mst0:mst1:mst2:addr_rule0:addr_rule1:addr_rule2, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rst_ni : signal is "xilinx.com:signal:reset:1.0 rst_ni RST";
  attribute X_INTERFACE_MODE of rst_ni : signal is "slave";
  attribute X_INTERFACE_PARAMETER of rst_ni : signal is "XIL_INTERFACENAME rst_ni, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of slv0_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 slv0 AWID";
  attribute X_INTERFACE_MODE of slv0_req_aw_id : signal is "slave";
  attribute X_INTERFACE_PARAMETER of slv0_req_aw_id : signal is "XIL_INTERFACENAME slv0, DATA_WIDTH 64, PROTOCOL AXI4, ID_WIDTH 1, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of slv0_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 slv0 AWADDR";
  attribute X_INTERFACE_INFO of slv0_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 slv0 AWLEN";
  attribute X_INTERFACE_INFO of slv0_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 slv0 AWSIZE";
  attribute X_INTERFACE_INFO of slv0_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 slv0 AWBURST";
  attribute X_INTERFACE_INFO of slv0_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 slv0 AWLOCK";
  attribute X_INTERFACE_INFO of slv0_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 slv0 AWCACHE";
  attribute X_INTERFACE_INFO of slv0_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 slv0 AWPROT";
  attribute X_INTERFACE_INFO of slv0_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 slv0 AWQOS";
  attribute X_INTERFACE_INFO of slv0_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 slv0 AWREGION";
  attribute X_INTERFACE_INFO of slv0_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 slv0 AWUSER";
  attribute X_INTERFACE_INFO of slv0_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 slv0 AWVALID";
  attribute X_INTERFACE_INFO of slv0_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 slv0 AWREADY";
  attribute X_INTERFACE_INFO of slv0_req_w_data : signal is "xilinx.com:interface:aximm:1.0 slv0 WDATA";
  attribute X_INTERFACE_INFO of slv0_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 slv0 WSTRB";
  attribute X_INTERFACE_INFO of slv0_req_w_last : signal is "xilinx.com:interface:aximm:1.0 slv0 WLAST";
  attribute X_INTERFACE_INFO of slv0_req_w_user : signal is "xilinx.com:interface:aximm:1.0 slv0 WUSER";
  attribute X_INTERFACE_INFO of slv0_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 slv0 WVALID";
  attribute X_INTERFACE_INFO of slv0_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 slv0 WREADY";
  attribute X_INTERFACE_INFO of slv0_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 slv0 BID";
  attribute X_INTERFACE_INFO of slv0_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 slv0 BRESP";
  attribute X_INTERFACE_INFO of slv0_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 slv0 BUSER";
  attribute X_INTERFACE_INFO of slv0_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 slv0 BVALID";
  attribute X_INTERFACE_INFO of slv0_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 slv0 BREADY";
  attribute X_INTERFACE_INFO of slv0_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 slv0 ARID";
  attribute X_INTERFACE_INFO of slv0_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 slv0 ARADDR";
  attribute X_INTERFACE_INFO of slv0_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 slv0 ARLEN";
  attribute X_INTERFACE_INFO of slv0_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 slv0 ARSIZE";
  attribute X_INTERFACE_INFO of slv0_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 slv0 ARBURST";
  attribute X_INTERFACE_INFO of slv0_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 slv0 ARLOCK";
  attribute X_INTERFACE_INFO of slv0_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 slv0 ARCACHE";
  attribute X_INTERFACE_INFO of slv0_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 slv0 ARPROT";
  attribute X_INTERFACE_INFO of slv0_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 slv0 ARQOS";
  attribute X_INTERFACE_INFO of slv0_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 slv0 ARREGION";
  attribute X_INTERFACE_INFO of slv0_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 slv0 ARUSER";
  attribute X_INTERFACE_INFO of slv0_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 slv0 ARVALID";
  attribute X_INTERFACE_INFO of slv0_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 slv0 ARREADY";
  attribute X_INTERFACE_INFO of slv0_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 slv0 RID";
  attribute X_INTERFACE_INFO of slv0_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 slv0 RDATA";
  attribute X_INTERFACE_INFO of slv0_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 slv0 RRESP";
  attribute X_INTERFACE_INFO of slv0_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 slv0 RLAST";
  attribute X_INTERFACE_INFO of slv0_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 slv0 RUSER";
  attribute X_INTERFACE_INFO of slv0_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 slv0 RVALID";
  attribute X_INTERFACE_INFO of slv0_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 slv0 RREADY";
  attribute X_INTERFACE_INFO of slv1_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 slv1 AWID";
  attribute X_INTERFACE_MODE of slv1_req_aw_id : signal is "slave";
  attribute X_INTERFACE_PARAMETER of slv1_req_aw_id : signal is "XIL_INTERFACENAME slv1, DATA_WIDTH 64, PROTOCOL AXI4, ID_WIDTH 1, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of slv1_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 slv1 AWADDR";
  attribute X_INTERFACE_INFO of slv1_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 slv1 AWLEN";
  attribute X_INTERFACE_INFO of slv1_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 slv1 AWSIZE";
  attribute X_INTERFACE_INFO of slv1_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 slv1 AWBURST";
  attribute X_INTERFACE_INFO of slv1_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 slv1 AWLOCK";
  attribute X_INTERFACE_INFO of slv1_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 slv1 AWCACHE";
  attribute X_INTERFACE_INFO of slv1_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 slv1 AWPROT";
  attribute X_INTERFACE_INFO of slv1_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 slv1 AWQOS";
  attribute X_INTERFACE_INFO of slv1_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 slv1 AWREGION";
  attribute X_INTERFACE_INFO of slv1_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 slv1 AWUSER";
  attribute X_INTERFACE_INFO of slv1_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 slv1 AWVALID";
  attribute X_INTERFACE_INFO of slv1_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 slv1 AWREADY";
  attribute X_INTERFACE_INFO of slv1_req_w_data : signal is "xilinx.com:interface:aximm:1.0 slv1 WDATA";
  attribute X_INTERFACE_INFO of slv1_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 slv1 WSTRB";
  attribute X_INTERFACE_INFO of slv1_req_w_last : signal is "xilinx.com:interface:aximm:1.0 slv1 WLAST";
  attribute X_INTERFACE_INFO of slv1_req_w_user : signal is "xilinx.com:interface:aximm:1.0 slv1 WUSER";
  attribute X_INTERFACE_INFO of slv1_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 slv1 WVALID";
  attribute X_INTERFACE_INFO of slv1_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 slv1 WREADY";
  attribute X_INTERFACE_INFO of slv1_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 slv1 BID";
  attribute X_INTERFACE_INFO of slv1_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 slv1 BRESP";
  attribute X_INTERFACE_INFO of slv1_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 slv1 BUSER";
  attribute X_INTERFACE_INFO of slv1_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 slv1 BVALID";
  attribute X_INTERFACE_INFO of slv1_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 slv1 BREADY";
  attribute X_INTERFACE_INFO of slv1_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 slv1 ARID";
  attribute X_INTERFACE_INFO of slv1_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 slv1 ARADDR";
  attribute X_INTERFACE_INFO of slv1_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 slv1 ARLEN";
  attribute X_INTERFACE_INFO of slv1_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 slv1 ARSIZE";
  attribute X_INTERFACE_INFO of slv1_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 slv1 ARBURST";
  attribute X_INTERFACE_INFO of slv1_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 slv1 ARLOCK";
  attribute X_INTERFACE_INFO of slv1_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 slv1 ARCACHE";
  attribute X_INTERFACE_INFO of slv1_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 slv1 ARPROT";
  attribute X_INTERFACE_INFO of slv1_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 slv1 ARQOS";
  attribute X_INTERFACE_INFO of slv1_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 slv1 ARREGION";
  attribute X_INTERFACE_INFO of slv1_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 slv1 ARUSER";
  attribute X_INTERFACE_INFO of slv1_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 slv1 ARVALID";
  attribute X_INTERFACE_INFO of slv1_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 slv1 ARREADY";
  attribute X_INTERFACE_INFO of slv1_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 slv1 RID";
  attribute X_INTERFACE_INFO of slv1_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 slv1 RDATA";
  attribute X_INTERFACE_INFO of slv1_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 slv1 RRESP";
  attribute X_INTERFACE_INFO of slv1_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 slv1 RLAST";
  attribute X_INTERFACE_INFO of slv1_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 slv1 RUSER";
  attribute X_INTERFACE_INFO of slv1_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 slv1 RVALID";
  attribute X_INTERFACE_INFO of slv1_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 slv1 RREADY";
  attribute X_INTERFACE_INFO of mst0_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 mst0 AWID";
  attribute X_INTERFACE_MODE of mst0_req_aw_id : signal is "master";
  attribute X_INTERFACE_PARAMETER of mst0_req_aw_id : signal is "XIL_INTERFACENAME mst0, DATA_WIDTH 64, PROTOCOL AXI4, ID_WIDTH 3, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of mst0_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 mst0 AWADDR";
  attribute X_INTERFACE_INFO of mst0_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 mst0 AWLEN";
  attribute X_INTERFACE_INFO of mst0_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 mst0 AWSIZE";
  attribute X_INTERFACE_INFO of mst0_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 mst0 AWBURST";
  attribute X_INTERFACE_INFO of mst0_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 mst0 AWLOCK";
  attribute X_INTERFACE_INFO of mst0_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 mst0 AWCACHE";
  attribute X_INTERFACE_INFO of mst0_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 mst0 AWPROT";
  attribute X_INTERFACE_INFO of mst0_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 mst0 AWQOS";
  attribute X_INTERFACE_INFO of mst0_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 mst0 AWREGION";
  attribute X_INTERFACE_INFO of mst0_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 mst0 AWUSER";
  attribute X_INTERFACE_INFO of mst0_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 mst0 AWVALID";
  attribute X_INTERFACE_INFO of mst0_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 mst0 AWREADY";
  attribute X_INTERFACE_INFO of mst0_req_w_data : signal is "xilinx.com:interface:aximm:1.0 mst0 WDATA";
  attribute X_INTERFACE_INFO of mst0_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 mst0 WSTRB";
  attribute X_INTERFACE_INFO of mst0_req_w_last : signal is "xilinx.com:interface:aximm:1.0 mst0 WLAST";
  attribute X_INTERFACE_INFO of mst0_req_w_user : signal is "xilinx.com:interface:aximm:1.0 mst0 WUSER";
  attribute X_INTERFACE_INFO of mst0_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 mst0 WVALID";
  attribute X_INTERFACE_INFO of mst0_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 mst0 WREADY";
  attribute X_INTERFACE_INFO of mst0_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 mst0 BID";
  attribute X_INTERFACE_INFO of mst0_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 mst0 BRESP";
  attribute X_INTERFACE_INFO of mst0_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 mst0 BUSER";
  attribute X_INTERFACE_INFO of mst0_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 mst0 BVALID";
  attribute X_INTERFACE_INFO of mst0_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 mst0 BREADY";
  attribute X_INTERFACE_INFO of mst0_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 mst0 ARID";
  attribute X_INTERFACE_INFO of mst0_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 mst0 ARADDR";
  attribute X_INTERFACE_INFO of mst0_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 mst0 ARLEN";
  attribute X_INTERFACE_INFO of mst0_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 mst0 ARSIZE";
  attribute X_INTERFACE_INFO of mst0_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 mst0 ARBURST";
  attribute X_INTERFACE_INFO of mst0_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 mst0 ARLOCK";
  attribute X_INTERFACE_INFO of mst0_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 mst0 ARCACHE";
  attribute X_INTERFACE_INFO of mst0_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 mst0 ARPROT";
  attribute X_INTERFACE_INFO of mst0_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 mst0 ARQOS";
  attribute X_INTERFACE_INFO of mst0_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 mst0 ARREGION";
  attribute X_INTERFACE_INFO of mst0_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 mst0 ARUSER";
  attribute X_INTERFACE_INFO of mst0_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 mst0 ARVALID";
  attribute X_INTERFACE_INFO of mst0_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 mst0 ARREADY";
  attribute X_INTERFACE_INFO of mst0_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 mst0 RID";
  attribute X_INTERFACE_INFO of mst0_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 mst0 RDATA";
  attribute X_INTERFACE_INFO of mst0_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 mst0 RRESP";
  attribute X_INTERFACE_INFO of mst0_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 mst0 RLAST";
  attribute X_INTERFACE_INFO of mst0_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 mst0 RUSER";
  attribute X_INTERFACE_INFO of mst0_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 mst0 RVALID";
  attribute X_INTERFACE_INFO of mst0_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 mst0 RREADY";
  attribute X_INTERFACE_INFO of mst1_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 mst1 AWID";
  attribute X_INTERFACE_MODE of mst1_req_aw_id : signal is "master";
  attribute X_INTERFACE_PARAMETER of mst1_req_aw_id : signal is "XIL_INTERFACENAME mst1, DATA_WIDTH 64, PROTOCOL AXI4, ID_WIDTH 3, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of mst1_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 mst1 AWADDR";
  attribute X_INTERFACE_INFO of mst1_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 mst1 AWLEN";
  attribute X_INTERFACE_INFO of mst1_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 mst1 AWSIZE";
  attribute X_INTERFACE_INFO of mst1_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 mst1 AWBURST";
  attribute X_INTERFACE_INFO of mst1_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 mst1 AWLOCK";
  attribute X_INTERFACE_INFO of mst1_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 mst1 AWCACHE";
  attribute X_INTERFACE_INFO of mst1_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 mst1 AWPROT";
  attribute X_INTERFACE_INFO of mst1_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 mst1 AWQOS";
  attribute X_INTERFACE_INFO of mst1_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 mst1 AWREGION";
  attribute X_INTERFACE_INFO of mst1_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 mst1 AWUSER";
  attribute X_INTERFACE_INFO of mst1_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 mst1 AWVALID";
  attribute X_INTERFACE_INFO of mst1_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 mst1 AWREADY";
  attribute X_INTERFACE_INFO of mst1_req_w_data : signal is "xilinx.com:interface:aximm:1.0 mst1 WDATA";
  attribute X_INTERFACE_INFO of mst1_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 mst1 WSTRB";
  attribute X_INTERFACE_INFO of mst1_req_w_last : signal is "xilinx.com:interface:aximm:1.0 mst1 WLAST";
  attribute X_INTERFACE_INFO of mst1_req_w_user : signal is "xilinx.com:interface:aximm:1.0 mst1 WUSER";
  attribute X_INTERFACE_INFO of mst1_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 mst1 WVALID";
  attribute X_INTERFACE_INFO of mst1_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 mst1 WREADY";
  attribute X_INTERFACE_INFO of mst1_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 mst1 BID";
  attribute X_INTERFACE_INFO of mst1_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 mst1 BRESP";
  attribute X_INTERFACE_INFO of mst1_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 mst1 BUSER";
  attribute X_INTERFACE_INFO of mst1_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 mst1 BVALID";
  attribute X_INTERFACE_INFO of mst1_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 mst1 BREADY";
  attribute X_INTERFACE_INFO of mst1_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 mst1 ARID";
  attribute X_INTERFACE_INFO of mst1_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 mst1 ARADDR";
  attribute X_INTERFACE_INFO of mst1_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 mst1 ARLEN";
  attribute X_INTERFACE_INFO of mst1_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 mst1 ARSIZE";
  attribute X_INTERFACE_INFO of mst1_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 mst1 ARBURST";
  attribute X_INTERFACE_INFO of mst1_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 mst1 ARLOCK";
  attribute X_INTERFACE_INFO of mst1_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 mst1 ARCACHE";
  attribute X_INTERFACE_INFO of mst1_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 mst1 ARPROT";
  attribute X_INTERFACE_INFO of mst1_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 mst1 ARQOS";
  attribute X_INTERFACE_INFO of mst1_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 mst1 ARREGION";
  attribute X_INTERFACE_INFO of mst1_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 mst1 ARUSER";
  attribute X_INTERFACE_INFO of mst1_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 mst1 ARVALID";
  attribute X_INTERFACE_INFO of mst1_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 mst1 ARREADY";
  attribute X_INTERFACE_INFO of mst1_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 mst1 RID";
  attribute X_INTERFACE_INFO of mst1_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 mst1 RDATA";
  attribute X_INTERFACE_INFO of mst1_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 mst1 RRESP";
  attribute X_INTERFACE_INFO of mst1_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 mst1 RLAST";
  attribute X_INTERFACE_INFO of mst1_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 mst1 RUSER";
  attribute X_INTERFACE_INFO of mst1_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 mst1 RVALID";
  attribute X_INTERFACE_INFO of mst1_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 mst1 RREADY";
  attribute X_INTERFACE_INFO of mst2_req_aw_id : signal is "xilinx.com:interface:aximm:1.0 mst2 AWID";
  attribute X_INTERFACE_MODE of mst2_req_aw_id : signal is "master";
  attribute X_INTERFACE_PARAMETER of mst2_req_aw_id : signal is "XIL_INTERFACENAME mst2, DATA_WIDTH 64, PROTOCOL AXI4, ID_WIDTH 3, ADDR_WIDTH 64, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of mst2_req_aw_addr : signal is "xilinx.com:interface:aximm:1.0 mst2 AWADDR";
  attribute X_INTERFACE_INFO of mst2_req_aw_len : signal is "xilinx.com:interface:aximm:1.0 mst2 AWLEN";
  attribute X_INTERFACE_INFO of mst2_req_aw_size : signal is "xilinx.com:interface:aximm:1.0 mst2 AWSIZE";
  attribute X_INTERFACE_INFO of mst2_req_aw_burst : signal is "xilinx.com:interface:aximm:1.0 mst2 AWBURST";
  attribute X_INTERFACE_INFO of mst2_req_aw_lock : signal is "xilinx.com:interface:aximm:1.0 mst2 AWLOCK";
  attribute X_INTERFACE_INFO of mst2_req_aw_cache : signal is "xilinx.com:interface:aximm:1.0 mst2 AWCACHE";
  attribute X_INTERFACE_INFO of mst2_req_aw_prot : signal is "xilinx.com:interface:aximm:1.0 mst2 AWPROT";
  attribute X_INTERFACE_INFO of mst2_req_aw_qos : signal is "xilinx.com:interface:aximm:1.0 mst2 AWQOS";
  attribute X_INTERFACE_INFO of mst2_req_aw_region : signal is "xilinx.com:interface:aximm:1.0 mst2 AWREGION";
  attribute X_INTERFACE_INFO of mst2_req_aw_user : signal is "xilinx.com:interface:aximm:1.0 mst2 AWUSER";
  attribute X_INTERFACE_INFO of mst2_req_aw_valid : signal is "xilinx.com:interface:aximm:1.0 mst2 AWVALID";
  attribute X_INTERFACE_INFO of mst2_rsp_aw_ready : signal is "xilinx.com:interface:aximm:1.0 mst2 AWREADY";
  attribute X_INTERFACE_INFO of mst2_req_w_data : signal is "xilinx.com:interface:aximm:1.0 mst2 WDATA";
  attribute X_INTERFACE_INFO of mst2_req_w_strb : signal is "xilinx.com:interface:aximm:1.0 mst2 WSTRB";
  attribute X_INTERFACE_INFO of mst2_req_w_last : signal is "xilinx.com:interface:aximm:1.0 mst2 WLAST";
  attribute X_INTERFACE_INFO of mst2_req_w_user : signal is "xilinx.com:interface:aximm:1.0 mst2 WUSER";
  attribute X_INTERFACE_INFO of mst2_req_w_valid : signal is "xilinx.com:interface:aximm:1.0 mst2 WVALID";
  attribute X_INTERFACE_INFO of mst2_rsp_w_ready : signal is "xilinx.com:interface:aximm:1.0 mst2 WREADY";
  attribute X_INTERFACE_INFO of mst2_rsp_b_id : signal is "xilinx.com:interface:aximm:1.0 mst2 BID";
  attribute X_INTERFACE_INFO of mst2_rsp_b_resp : signal is "xilinx.com:interface:aximm:1.0 mst2 BRESP";
  attribute X_INTERFACE_INFO of mst2_rsp_b_user : signal is "xilinx.com:interface:aximm:1.0 mst2 BUSER";
  attribute X_INTERFACE_INFO of mst2_rsp_b_valid : signal is "xilinx.com:interface:aximm:1.0 mst2 BVALID";
  attribute X_INTERFACE_INFO of mst2_req_b_ready : signal is "xilinx.com:interface:aximm:1.0 mst2 BREADY";
  attribute X_INTERFACE_INFO of mst2_req_ar_id : signal is "xilinx.com:interface:aximm:1.0 mst2 ARID";
  attribute X_INTERFACE_INFO of mst2_req_ar_addr : signal is "xilinx.com:interface:aximm:1.0 mst2 ARADDR";
  attribute X_INTERFACE_INFO of mst2_req_ar_len : signal is "xilinx.com:interface:aximm:1.0 mst2 ARLEN";
  attribute X_INTERFACE_INFO of mst2_req_ar_size : signal is "xilinx.com:interface:aximm:1.0 mst2 ARSIZE";
  attribute X_INTERFACE_INFO of mst2_req_ar_burst : signal is "xilinx.com:interface:aximm:1.0 mst2 ARBURST";
  attribute X_INTERFACE_INFO of mst2_req_ar_lock : signal is "xilinx.com:interface:aximm:1.0 mst2 ARLOCK";
  attribute X_INTERFACE_INFO of mst2_req_ar_cache : signal is "xilinx.com:interface:aximm:1.0 mst2 ARCACHE";
  attribute X_INTERFACE_INFO of mst2_req_ar_prot : signal is "xilinx.com:interface:aximm:1.0 mst2 ARPROT";
  attribute X_INTERFACE_INFO of mst2_req_ar_qos : signal is "xilinx.com:interface:aximm:1.0 mst2 ARQOS";
  attribute X_INTERFACE_INFO of mst2_req_ar_region : signal is "xilinx.com:interface:aximm:1.0 mst2 ARREGION";
  attribute X_INTERFACE_INFO of mst2_req_ar_user : signal is "xilinx.com:interface:aximm:1.0 mst2 ARUSER";
  attribute X_INTERFACE_INFO of mst2_req_ar_valid : signal is "xilinx.com:interface:aximm:1.0 mst2 ARVALID";
  attribute X_INTERFACE_INFO of mst2_rsp_ar_ready : signal is "xilinx.com:interface:aximm:1.0 mst2 ARREADY";
  attribute X_INTERFACE_INFO of mst2_rsp_r_id : signal is "xilinx.com:interface:aximm:1.0 mst2 RID";
  attribute X_INTERFACE_INFO of mst2_rsp_r_data : signal is "xilinx.com:interface:aximm:1.0 mst2 RDATA";
  attribute X_INTERFACE_INFO of mst2_rsp_r_resp : signal is "xilinx.com:interface:aximm:1.0 mst2 RRESP";
  attribute X_INTERFACE_INFO of mst2_rsp_r_last : signal is "xilinx.com:interface:aximm:1.0 mst2 RLAST";
  attribute X_INTERFACE_INFO of mst2_rsp_r_user : signal is "xilinx.com:interface:aximm:1.0 mst2 RUSER";
  attribute X_INTERFACE_INFO of mst2_rsp_r_valid : signal is "xilinx.com:interface:aximm:1.0 mst2 RVALID";
  attribute X_INTERFACE_INFO of mst2_req_r_ready : signal is "xilinx.com:interface:aximm:1.0 mst2 RREADY";
  attribute X_INTERFACE_INFO of rule0_idx : signal is "My:user:addr_map:1.0 addr_rule0 idx";
  attribute X_INTERFACE_MODE of rule0_idx : signal is "slave";
  attribute X_INTERFACE_INFO of rule0_start_addr : signal is "My:user:addr_map:1.0 addr_rule0 start_addr";
  attribute X_INTERFACE_INFO of rule0_end_addr : signal is "My:user:addr_map:1.0 addr_rule0 end_addr";
  attribute X_INTERFACE_INFO of rule1_idx : signal is "My:user:addr_map:1.0 addr_rule1 idx";
  attribute X_INTERFACE_MODE of rule1_idx : signal is "slave";
  attribute X_INTERFACE_INFO of rule1_start_addr : signal is "My:user:addr_map:1.0 addr_rule1 start_addr";
  attribute X_INTERFACE_INFO of rule1_end_addr : signal is "My:user:addr_map:1.0 addr_rule1 end_addr";
  attribute X_INTERFACE_INFO of rule2_idx : signal is "My:user:addr_map:1.0 addr_rule2 idx";
  attribute X_INTERFACE_MODE of rule2_idx : signal is "slave";
  attribute X_INTERFACE_INFO of rule2_start_addr : signal is "My:user:addr_map:1.0 addr_rule2 start_addr";
  attribute X_INTERFACE_INFO of rule2_end_addr : signal is "My:user:addr_map:1.0 addr_rule2 end_addr";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "axi_xbar_v,Vivado 2024.2";
begin
end;
