#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 08 15:01:32 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim reg_to_axi_tb_behav -key {Behavioral:sim_1:Functional:reg_to_axi_tb} -tclbatch reg_to_axi_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/yanry/dma/reg_to_axi_test/reg_to_axi_tb_behav.wcfg -log simulate.log"
xsim reg_to_axi_tb_behav -key {Behavioral:sim_1:Functional:reg_to_axi_tb} -tclbatch reg_to_axi_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/yanry/dma/reg_to_axi_test/reg_to_axi_tb_behav.wcfg -log simulate.log

