domain_path: /home/yanry/dma/z19_MP_iDMA/vitis_prj_1/z19_ddr_cdma/export/z19_ddr_cdma/sw/standalone_psu_cortexa53_0
app_src_dir: /home/data/tools/Xilinx24/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
