domain_path: /home/yanry/dma/z19_MP_iDMA_xbar/vitis_prj/z19_MP_iDMA_xbar/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/data/tools/Xilinx24/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
