#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 18 17:19:54 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim dma_axi_tb_behav -key {Behavioral:sim_1:Functional:dma_axi_tb} -tclbatch dma_axi_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/yanry/dma/idma_axi_test/dma_axi_tb_behav.wcfg -log simulate.log"
xsim dma_axi_tb_behav -key {Behavioral:sim_1:Functional:dma_axi_tb} -tclbatch dma_axi_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/yanry/dma/idma_axi_test/dma_axi_tb_behav.wcfg -log simulate.log

